### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'model_s_300_w_5.bin'

### ISSUE THREAD

**Issue by SeekPoint** [Erbenner/fsauor2018#1]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/fsauor2018-1$ python3.6 main.py --type train --label 2 --iter 6600
WARNING:tensorflow:From /media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/fsauor2018-1/load_model.py:41: BasicLSTMCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is deprecated, please use tf.nn.rnn_cell.LSTMCell, which supports all the feature this cell currently has. Please replace the existing code with tf.nn.rnn_cell.LSTMCell(name='basic_lstm_cell').
WARNING:tensorflow:From /media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/fsauor2018-1/load_model.py:131: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Traceback (most recent call last):
  File "main.py", line 198, in <module>
    train(**vars(FLAGS))
  File "main.py", line 26, in train
    data = Load_batch(method=kwargs['type'], label=kwargs['label'])
  File "/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/fsauor2018-1/load_batch.py", line 39, in __init__
    self.model = KeyedVectors.load_word2vec_format(self.model_path, binary=True)
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/keyedvectors.py", line 1494, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/usr/local/lib/python3.6/dist-packages/gensim/models/utils_any2vec.py", line 342, in _load_word2vec_format
    with utils.smart_open(fname) as fin:
  File "/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py", line 439, in smart_open
    return open(uri, mode, ignore_ext=ignore_extension, transport_params=transport_params, **scrubbed_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py", line 307, in open
    errors=errors,
  File "/usr/local/lib/python3.6/dist-packages/smart_open/smart_open_lib.py", line 498, in _shortcut_open
    return _builtin_open(parsed_uri.uri_path, mode, buffering=buffering, **open_kwargs)
FileNotFoundError: [Errno 2] No such file or directory: 'model_s_300_w_5.bin'
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/fsauor2018-1$

**Comment by viewlei** [comment]
这个是word2vec训练得到的词向量（语言模型），你可以用word2vec.py文件对自己本地的数据集进行无监督训练得到该文件。
